## Scalar ##

In [2]:
x = 'salman arya'
x

'salman arya'

In [3]:
type(x)

str

In [4]:
y = 'test'
y

'test'

In [6]:
sum = x + ' ' + y
sum

'salman arya test'

## Vector ##

In [8]:
import numpy as np

In [10]:
x = np.array([25,2,5])
x

array([25,  2,  5])

In [11]:
print(x)

[25  2  5]


Untuk di ipynb gamasalah di panggil langsung (x) atau mau di print. tetapi di App.py wajib di print

In [12]:
len(x)

3

In [14]:
# baris x column
x.shape

(3,)

In [16]:
x[1]

2

In [17]:
type(x[1])

numpy.int32

## Vector Transpose ##

In [27]:
import numpy as np
# tambah kurung [] lagi untuk buat dimensi baru, jangan lupa tanda koma
# y = np.array([[2,2,2],[2,1,3],[25,2,5]])
y = np.array([[25,2,5]])
y

array([[25,  2,  5]])

In [28]:
y.shape

(1, 3)

In [29]:
y_t = np.transpose(y)
print(y_t)

[[25]
 [ 2]
 [ 5]]


In [30]:
y_t_baru = y.T
y_t_baru

array([[25],
       [ 2],
       [ 5]])

In [31]:
y_t_baru.shape

(3, 1)

## Norm ##

$L^1$ Norm

In [13]:
import numpy as np
x = np.array([25,2,5])
x

array([25,  2,  5])

In [7]:
np.abs(25) + np.abs(2) + np.abs(5)

32

In [15]:
np.dot(x,x)

654

In [8]:
(25**2 + 2**2 + 5**2)

654

L2 Norm

In [3]:
# vector [25, 2, 5]
# 1. Pangkatkan setiap nilai vector
# 2. hasil dijumlahkan
# 3. hasil dair penjumlahan diambil akarnya

(25**2 + 2**2 + 5**2)**(1/2)

25.573423705088842

In [4]:
import numpy as np
x = np.array([25,2,5])
x

array([25,  2,  5])

In [5]:
np.linalg.norm(x)

25.573423705088842

In [6]:
round(np.linalg.norm(x),3)

25.573

Max Norm

In [22]:
import numpy as np
np.max([np.abs(25),  np.abs(2), np.abs(5)])

25